### ISSUE TITLE
server01.c浏览器访问卡住

### ISSUE THREAD

**Issue by cygmris** [jaykizhou/php-server#1]
返回的响应中没有指定Data的长度,导致浏览器一直在等待,无法显示页面。

**Comment by jaykizhou** [comment]
感谢指正。不过原因不是响应没有指定长度，而是下面循环读取客户端请求数据有误！
    // 读取客户端请求
    while(read(clnt_sock, buf, sizeof(buf) -1) > 0){
        printf("%s", buf);
    }
非常感谢！
